waterford_colours:
  WFDMCM: "MATT CASHMERE"
  WFDMLG: "MATT LIGHT GREY"
  WFDMSG: "MATT SAGE GREEN"
  WFDMWH: "MATT WHITE"
  WFDMIB: "MATT BLUE"
  WFDWCM: "WOODGRAIN CASHMERE"
  WFDWLG: "WOODGRAIN LIGHT GREY"
  WFDWSG: "WOODGRAIN SAGE GREEN"
  WFDWWH: "WOODGRAIN WHITE"
  WFDWIB: "WOODGRAIN BLUE"