kk_main_range:

  "01":
    item_description: "720 BASE 300"

    item_type: "cabinet_unit"

    cabinet:
      category: "base"
      subtype: "highline"
      height: 720
      width: 300
      depth: 570

    packs:
      - role: "main_pack"
        pattern: "BNBxBA300"
        quantity: 1

    fronts:
      - type: "door"
        description: "300 Door"
        size: "715X296"
        height: 715
        width: 296
        quantity: 1
        drilling: "T98 B98"

    hardware:
      hinges: 2
      mount_plates: 2

  "02":
    item_description: "720 BASE 400"

    item_type: "cabinet_unit"

    cabinet:
      category: "base"
      subtype: "highline"
      height: 720
      width: 400
      depth: 570

      packs:
      - role: "main_pack"
        pattern: "BNBxBA400"
        quantity: 1

    fronts:
      - type: "door"
        description: "400 Door"
        size: "715X396"
        height: 715
        width: 396
        quantity: 1
        drilling: "T98 B98"

    hardware:
      hinges: 2
      mount_plates: 2

  "03":
    item_description: "720 BASE 500"

    item_type: "cabinet_unit"

    cabinet:
      category: "base"
      subtype: "highline"
      height: 720
      width: 500
      depth: 570

      packs:
      - role: "main_pack"
        pattern: "BNBxBA500"
        quantity: 1

    fronts:
      - type: "door"
        description: "500 Door"
        size: "715X496"
        height: 715
        width: 496
        quantity: 1
        drilling: "T98 B98"

    hardware:
      hinges: 2
      mount_plates: 2

  "04":
    item_description: "720 BASE 600"

    item_type: "cabinet_unit"

    cabinet:
      category: "base"
      subtype: "highline"
      height: 720
      width: 600
      depth: 570

      packs:
      - role: "main_pack"
        pattern: "BNBxBA600"
        quantity: 1

    fronts:
      - type: "door"
        description: "600 Door"
        size: "715X596"
        height: 715
        width: 596
        quantity: 1
        drilling: "T98 B98"

    hardware:
      hinges: 2
      mount_plates: 2

  "05":
    item_description: "720 BASE UNDER OVEN 600"

    item_type: "cabinet_unit"

    cabinet:
      category: "base"
      subtype: "oven_housing"
      height: 720
      width: 600
      depth: 570
      
      packs:
      - role: "main_pack"
        pattern: "BNBxUO600"
        quantity: 1

    fronts:
      - type: "filler"
        description: "600 Under-Oven Filler"
        size: "110X596"
        height: 110
        width: 596
        quantity: 1
        drilling: null

    hardware: {}

  "06":
    item_description: "720 BASE FULL DRW 600"

    item_type: "cabinet_unit"

    cabinet:
      category: "base"
      subtype: "drawer"
      height: 720
      width: 600
      depth: 570

      packs:
      - role: "main_pack"
        pattern: "BNBxBD600"
        quantity: 1

    fronts:
      - type: "drawer"
        description: "600 Standard Drawer"
        size: "140X596"
        height: 140
        width: 596
        quantity: 1
        drilling: "Std Drawer Drilling"

      - type: "drawer"
        description: "600 Pan Drawer"
        size: "283X596"
        height: 283
        width: 596
        quantity: 2
        drilling: "Pan Drawer Drilling"

    hardware:
      drawerbox_3_set: 1

  "07":
    item_description: "720 BASE FULL DRW 800"

    item_type: "cabinet_unit"

    cabinet:
      category: "base"
      subtype: "drawer"
      height: 720
      width: 800
      depth: 570

      packs:
      - role: "main_pack"
        pattern: "BNBxBD800"
        quantity: 1

    fronts:
      - type: "drawer"
        description: "800 Standard Drawer"
        size: "140X796"
        height: 140
        width: 796
        quantity: 1
        drilling: "Std Drawer Drilling"

      - type: "drawer"
        description: "800 Pan Drawer"
        size: "283X596"
        height: 283
        width: 796
        quantity: 2
        drilling: "Pan Drawer Drilling"

    hardware:
      drawerbox_3_set: 1
      
  "08":
    item_description: "720 BASE 1000"

    item_type: "cabinet_unit"

    cabinet:
      category: "base"
      subtype: "highline"
      height: 720
      width: 1000
      depth: 570

      packs:
      - role: "main_pack"
        pattern: "BNBxBA1000"
        quantity: 1

    fronts:
      - type: "door"
        description: "500 Door"
        size: "715X496"
        height: 715
        width: 496
        quantity: 2
        drilling: "T98 B98"

    hardware:
      hinges: 2
      mount_plates: 2

  "09":
    item_description: "720 BASE BLIND CNR 1000"

    item_type: "cabinet_unit"

    cabinet:
      category: "base"
      subtype: "blind_corner"
      height: 720
      width: 1000
      depth: 570

      packs:
      - role: "main_pack"
        pattern: "BNBxBA1000"
        quantity: 1

      - role: "blanking_pack"
        pattern: "BNBWBBP72"
        quantity: 1

    fronts:
      - type: "door"
        description: "500 Door"
        size: "715X496"
        height: 715
        width: 496
        quantity: 1
        drilling: "T98 B98"

    hardware:
      hinges: 2
      mount_plates: 2

  "11":
    item_description: "720 WALL 300"

    item_type: "cabinet_unit"

    cabinet:
      category: "wall"
      subtype: "standard"
      height: 720
      width: 300
      depth: 330

      packs:
      - role: "main_pack"
        pattern: "BNBxWL300"
        quantity: 1

    fronts:
      - type: "door"
        description: "300 Door"
        size: "715X296"
        height: 715
        width: 296
        quantity: 1
        drilling: "T98 B98"

    hardware:
      hinges: 2
      mount_plates: 2

  "12":
    item_description: "720 WALL 400"

    item_type: "cabinet_unit"

    cabinet:
      category: "wall"
      subtype: "standard"
      height: 720
      width: 400
      depth: 330

      packs:
      - role: "main_pack"
        pattern: "BNBxWL400"
        quantity: 1

    fronts:
      - type: "door"
        description: "400 Door"
        size: "715X396"
        height: 715
        width: 396
        quantity: 1
        drilling: "T98 B98"

    hardware:
      hinges: 2
      mount_plates: 2

  "13":
    item_description: "720 WALL 500"

    item_type: "cabinet_unit"

    cabinet:
      category: "wall"
      subtype: "standard"
      height: 720
      width: 500
      depth: 330

      packs:
      - role: "main_pack"
        pattern: "BNBxWL500"
        quantity: 1

    fronts:
      - type: "door"
        description: "500 Door"
        size: "715X496"
        height: 715
        width: 496
        quantity: 1
        drilling: "T98 B98"

    hardware:
      hinges: 2
      mount_plates: 2

  "14":
    item_description: "720 WALL 600"

    item_type: "cabinet_unit"

    cabinet:
      category: "wall"
      subtype: "standard"
      height: 720
      width: 600
      depth: 330

      packs:
      - role: "main_pack"
        pattern: "BNBxWL600"
        quantity: 1

    fronts:
      - type: "door"
        description: "600 Door"
        size: "715X596"
        height: 715
        width: 596
        quantity: 1
        drilling: "T98 B98"

    hardware:
      hinges: 2
      mount_plates: 2

  "15":
    item_description: "720 WALL 1000"

    item_type: "cabinet_unit"

    cabinet:
      category: "wall"
      subtype: "standard"
      height: 720
      width: 1000
      depth: 330

      packs:
      - role: "main_pack"
        pattern: "BNBxWL1000"
        quantity: 1

    fronts:
      - type: "door"
        description: "500 Door"
        size: "715X496"
        height: 715
        width: 496
        quantity: 2
        drilling: "T98 B98"

    hardware:
      hinges: 4
      mount_plates: 4

  "16":
    item_description: "720 WALL BLIND CNR 600"

    item_type: "cabinet_unit"

    cabinet:
      category: "wall"
      subtype: "blind_corner"
      height: 720
      width: 600
      depth: 330

      packs:
      - role: "main_pack"
        pattern: "BNBxWL600"
        quantity: 1

      packs:
      - role: "blanking_pack"
        pattern: "BNBWWBP72"
        quantity: 1

    fronts:
      - type: "door"
        description: "500 Door"
        size: "715X296"
        height: 715
        width: 296
        quantity: 1
        drilling: "T98 B98"

    hardware:
      hinges: 2
      mount_plates: 2

  "18":
    item_description: "360 BRIDGE 500"

    item_type: "cabinet_unit"

    cabinet:
      category: "wall"
      subtype: "bridge"
      height: 360
      width: 500
      depth: 330

      packs:
      - role: "main_pack"
        pattern: "BNBxBR500"
        quantity: 1

    fronts:
      - type: "door"
        description: "500 Bridging Door"
        size: "355X496"
        height: 355
        width: 496
        quantity: 1
        drilling: "Flap Stay Drilling"

    hardware:
      flap_stay: 1

  "19":
    item_description: "360 BRIDGE 600"

    item_type: "cabinet_unit"

    cabinet:
      category: "wall"
      subtype: "bridge"
      height: 360
      width: 600
      depth: 330

      packs:
      - role: "main_pack"
        pattern: "BNBxBR600"
        quantity: 1

    fronts:
      - type: "door"
        description: "600 Bridging Door"
        size: "355X596"
        height: 355
        width: 596
        quantity: 1
        drilling: "Flap Stay Drilling"

    hardware:
      flap_stay: 1

  "20":
    item_description: "1970 LARDER 500"

    item_type: "cabinet_unit"

    cabinet:
      category: "tall"
      subtype: "larder"
      height: 1970
      width: 500
      depth: 570

      packs:
      - role: "side_pack"
        pattern: "BNBxLTEP"
        quantity: 1

      - role: "mid_pack"
        pattern: "BNBxL500MP"
        quantity: 1

    fronts:
      - type: "door"
        description: "500 Upper Larder Door"
        size: "1245X496"
        height: 1245
        width: 496
        quantity: 1
        drilling: "T98 B616 B98"

      - type: "door"
        description: "500 Lower Larder Door"
        size: "715X496"
        height: 715
        width: 496
        quantity: 1
        drilling: "T98 B98"

    hardware:
      hinges: 5
      mount_plates: 5

  "21":
    item_description: "1970 DOUBLE OVEN 500"

    item_type: "cabinet_unit"

    cabinet:
      category: "tall"
      subtype: "double_oven_housing"
      height: 1970
      width: 600
      depth: 570

      packs:
      - role: "side_pack"
        pattern: "BNBxLTEP"
        quantity: 1

      - role: "mid_pack"
        pattern: "BNBxL600MP"
        quantity: 1

    fronts:
      - type: "door"
        description: "600 Upper Double Oven Door"
        size: "490X596"
        height: 490
        width: 596
        quantity: 1
        drilling: "T98 B98"

      - type: "door"
        description: "600 Lower Double Oven Door"
        size: "570X596"
        height: 570
        width: 596
        quantity: 1
        drilling: "T98 B98"

    hardware:
      hinges: 4
      mount_plates: 4
      
  "22":
    item_description: "1970 FRIDGE/FREEZER 70/30 600"

    item_type: "cabinet_unit"

    cabinet:
      category: "tall"
      subtype: "fridge_freezer_housing"
      height: 1970
      width: 600
      depth: 570

      packs:
      - role: "side_pack"
        pattern: "BNBxLTEP"
        quantity: 1

      - role: "mid_pack"
        pattern: "BNBxL600MP"
        quantity: 1

    fronts:
      - type: "door"
        description: "600 Upper Double Oven Door"
        size: "490X596"
        height: 490
        width: 596
        quantity: 1
        drilling: "T98 B98"

      - type: "door"
        description: "600 Lower Double Oven Door"
        size: "570X596"
        height: 570
        width: 596
        quantity: 1
        drilling: "T98 B98"

    hardware:
      hinges: 4
      mount_plates: 4

  "23":
    item_description: "150H Plinth"

    item_type: "accessory"

    accessory:
      category: "profile"
      subtype: "plinth"

      length: 2745
      height: 150
      depth: 18

  "24":
    item_description: "Multi-Purpose Rail"

    item_type: "accessory"

    accessory:
      category: "profile"
      subtype: "multi_purpose_rail"

      length: 2745
      height: 56
      depth: 36

  "25":
    item_description: "Roll of Edging Tape 10M"

    item_type: "accessory"

    accessory:
      category: "consumable"
      subtype: "edging"

      length: 50000
      width: 22
      depth: 1

  "26":
    item_description: "Sample Door"

    item_type: "promotional"

    promotional:
      category: "frontal"
      subtype: "sample_door"

      height: 570
      width: 396
      depth: 18

  "27":
    item_description: "600 Appliance Door"

    item_type: "accessory"

    accessory:
      category: "frontal"
      subtype: "appliance_door"

      height: 715
      width: 596
      depth: 18

  "28":
    item_description: "Base End Panel"

    item_type: "accessory"

    accessory:
      category: "frontal"
      subtype: "end_panel"

      height: 900
      width: 600
      depth: 18

  "30":
    item_description: "Tall End Panel"

    item_type: "accessory"

    accessory:
      category: "frontal"
      subtype: "end_panel"

      height: 2400
      width: 600
      depth: 18
      
  "22":
    item_description: "1970 SINGLE OVEN 600"

    item_type: "cabinet_unit"

    cabinet:
      category: "tall"
      subtype: "oven_housing"
      height: 1970
      width: 600
      depth: 570

      packs:
      - role: "side_pack"
        pattern: "BNBxLTEP"
        quantity: 1

      - role: "mid_pack"
        pattern: "BNBxL600MP"
        quantity: 1

    fronts:
      - type: "door"
        description: "600 Upper Single Oven Door"
        size: "645X596"
        height: 645
        width: 596
        quantity: 1
        drilling: "T98 B98"

      - type: "door"
        description: "600 Lower Single Oven Door"
        size: "715X596"
        height: 715
        width: 596
        quantity: 1
        drilling: "T98 B98"

    hardware:
      hinges: 4
      mount_plates: 4