kk_door_colours:
  "00": gloss_white
  "01": gloss_cashmere
  "02": gloss_light_grey
  "03": gloss_dust_grey
  "04": gloss_graphite
  "05": matt_white
  "06": matt_cashmere
  "07": matt_light_grey
  "08": matt_dust_grey
  "09": matt_graphite
  "10": carcase_white
  "11": matt_sage_green
  "12": carcase_light_grey
  "13": matt_indigo_blue
  "14": carcase_urban_oak
  "15": antique_white
  "16": matt_dove_grey
  "21": matt_taupe_grey
  "22": urban_oak
  "30": alvic_gloss_white
  "31": alvic_gloss_cashmere
  "32": alvic_gloss_light_grey
  "33": alvic_matt_white
  "34": alvic_matt_cashmere
  "35": alvic_matt_light_grey
  "36": alvic_matt_aquamarine
  "37": alvic_matt_blue
  "38": alvic_matt_agave_green
  "40": value_matt_snow_white
  "41": value_matt_light_grey
  "42": value_matt_cashmere
  "43": value_matt_urban_oak
  "44": value_matt_alby_blue
  "45": value_matt_smoke_green
  "50": woodgrain_white
  "51": woodgrain_cashmere
  "52": woodgrain_light_grey
  "53": woodgrain_sage_green